### ISSUE TITLE
 Starting a new export removes the results of previous export during initial clean up (Mac)

### ISSUE THREAD

**Issue by GoranRista** [davidhealey/hise-exporter#17]
Let's say we have 2 projects: A and B. 
We run only Project A (plugins). Upon completion, the exporter places the compiled plugins under the "Builds>MacOSX>build>Release" folder in Binaries of Project A.
We then cue Project B to compile plugins. As soon as the process is started, the Exporter deletes the "Builds" folder in Project A, thus deleting all plugins previously compiled plugins of Project A. 
One step forward, one step back :)

**Comment by GoranRista** [comment]
This happens on PC as well, but it is not an issue, since the compiled plugins are placed in the "Compiled" folder, so they are not affected when the Builds folder is deleted.
Perhaps the easiest solution is to change the location of compiled plugins on Mac and place them under a new folder in "Binaries>Compiled>Mac".

**Comment by davidhealey** [comment]
The compiler (xcode) places the compiled binary in the builds folder, then my app copies it to the packaging/darwin folder. When it runs the next build (of the same project and assuming your exporting a different project type) it first runs the HISE build clean command to make sure there are no intermediate files from the previous project that could mess up the build.

Loading a completely separate project should have no effect on other projects, but we know there is something weird happening on your system that is causing cross project issues.

**Comment by GoranRista** [comment]
Remember that this is now Mac. The other issue is on PC. Where should I be retrieving the compiled plugins from?

**Comment by GoranRista** [comment]
I found the darwin folder you mentioned and can see they are copied there. Great. So that is not an issue then :) Thank you.
